### ISSUE TITLE
First class function behaviour with Vectors?

### ISSUE THREAD

**Issue by uqtredd1** [andreaferretti/neo#13]
It is possible to pass procedures to other procedures in nim, something like this for floats:

![image](https://user-images.githubusercontent.com/16814152/28498584-23db4ec0-6fe4-11e7-8167-e168876cc719.png)

However, attempting this with neo Vectors:
![image](https://user-images.githubusercontent.com/16814152/28498601-5d500466-6fe4-11e7-9b66-8d2d6ca804db.png)

Fails during compilation, with "Error: cannot instantiate: 'Vector'"

Is it possible to replicate this behaviour with vectors at all? This would be useful for (amongst many other things), programming numerical integration schemes such as the [runge-kutta algorithms](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods).

![image](https://user-images.githubusercontent.com/16814152/28498679-363d6204-6fe6-11e7-895c-3fd21e359322.png)

Thanks,
Tom

**Comment by andreaferretti** [comment]
Hi @uqtredd1 you can definitely higher order functions in Nim. The catch in your example is that `Vector` is generic, hence it is not a concrete type. In your example you may want to try - for instance - `Vector[float64]`

**Comment by mratsim** [comment]
@uqtredd1  you can use triple backquote + Nim to format Nim code like in the Nim forum. We can't copy paste your examples.

Like Andrea said, you have to specify either a concrete type (Vector[float]) or a generic type (Vector[T]) to Nim.

Here is an example that compiles:

```Nim
import neo, future

proc g[T](x: Vector[T]): Vector[T] =
  result = 2.T * x

proc h[T](g: Vector[T] -> Vector[T],
          x: Vector[T]): Vector[T] =
  result = g(x)

echo h[float](g, vector(1.0,2.0))
```

I don't know why the compiler complains with `Cannot instantiate T` if we use `h` instead of `h[float]` though.

PS: The `->` syntax is introduced by Nim future module for higher-order functions
