### ISSUE TITLE
[IndexError] Creating matrix from sequences of unequal length

### ISSUE THREAD

**Issue by narimiran** [andreaferretti/neo#20]
Nobody sane would/should do something like this, but even still—should this be caught?

```nim
let
  s1 = @[3.5, 6.5]
  s2 = @[1.0, 2.0, 5.0]

let m1 = matrix(@[s1, s2])
echo m1
# [ [ 3.5	6.5 ]
#   [ 1.0	2.0 ] ]
```

Reverse the order, so the first row is larger:
```nim
let m2 = matrix(@[s2, s1])
echo m2
# Error: unhandled exception: index out of bounds [IndexError]
```

---

Should the lengths be checked before calling `makeMatrixIJ` template? Something like this:
```nim
proc matrix*[A](xs: seq[seq[A]], order = colMajor): Matrix[A] =
  for x in xs:
    checkDim(xs[0].len == x.len, "The dimensions do not match")
  makeMatrixIJ(A, xs.len, xs[0].len, xs[i][j], order)
```

I'm willing to write a PR, just let me know if/how this should be handled.

**Comment by andreaferretti** [comment]
Yes, it looks like a missing dimension check. The way you handle it is fine, just put it in a `when compileOption("assertions"):` to avoid calling checkdim in a loop, since it is a no-op unless assertions are active: https://github.com/unicredit/neo/blob/master/neo/core.nim#L26-L30

Maybe the C compiler removes the loop altogether but still
