### ISSUE TITLE
log function compiles but fails on run

### ISSUE THREAD

**Issue by freevryheid** [andreaferretti/neo#31]
<code>

import neo

let v1 = vector(1.0, 2.0, 3.0)

let v2 = log(v1)

</code>

**Comment by andreaferretti** [comment]
I see what happened here. It used to be the case that (in the module `math`) `log` was a function of two parameters `log(x, base)` with a default for base of (I think) `e`.

In recent versions of Nim, the default was removed, and as such expressions such as `log(3.0)` do not compile anymore (the base parameter is required). The way universal functions are generated expect a similar one parameter function for the scalar case. Notice that `log2` and `log10` are still working, since they have an implied base.

I am going to remove `neo.log`, since - as you point out - it does not work anymore. You can get back the functionality by doing something like

```nim
import math
import neo

proc mylog[T: SomeFloat](x: T): T = log(x, e) # or whatever base you prefer
makeUniversal(mylog)

let v1 = vector(1.0, 2.0, 3.0)
let v2 = mylog(v1)
```

**Comment by freevryheid** [comment]
I see there is now a ln function for natural log.

**Comment by andreaferretti** [comment]
Thank you, added it
